package com.hotelbooking.model;
// default package
// Generated Nov 13, 2022, 7:30:48 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Agent generated by hbm2java
 */
@Entity
@Table(name = "agent", catalog = "hotel_booking")
public class Agent implements java.io.Serializable {

	private int agentId;
	private String displayName;
	private String bio;
	private String coverImg;
	private String avatarImg;
	private String contactNum;
	private String email;
	private String address;
	private Set<Hotel> hotels = new HashSet<Hotel>(0);

	public Agent() {
	}

	public Agent(int agentId) {
		this.agentId = agentId;
	}

	public Agent(int agentId, String displayName, String bio, String coverImg, String avatarImg, String contactNum,
			String email, String address, Set<Hotel> hotels) {
		this.agentId = agentId;
		this.displayName = displayName;
		this.bio = bio;
		this.coverImg = coverImg;
		this.avatarImg = avatarImg;
		this.contactNum = contactNum;
		this.email = email;
		this.address = address;
		this.hotels = hotels;
	}

	@Id

	@Column(name = "Agent_ID", unique = true, nullable = false)
	public int getAgentId() {
		return this.agentId;
	}

	public void setAgentId(int agentId) {
		this.agentId = agentId;
	}

	@Column(name = "Display_Name")
	public String getDisplayName() {
		return this.displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	@Column(name = "Bio")
	public String getBio() {
		return this.bio;
	}

	public void setBio(String bio) {
		this.bio = bio;
	}

	@Column(name = "Cover_Img")
	public String getCoverImg() {
		return this.coverImg;
	}

	public void setCoverImg(String coverImg) {
		this.coverImg = coverImg;
	}

	@Column(name = "Avatar_Img")
	public String getAvatarImg() {
		return this.avatarImg;
	}

	public void setAvatarImg(String avatarImg) {
		this.avatarImg = avatarImg;
	}

	@Column(name = "Contact_Num")
	public String getContactNum() {
		return this.contactNum;
	}

	public void setContactNum(String contactNum) {
		this.contactNum = contactNum;
	}

	@Column(name = "Email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "Address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "agent")
	public Set<Hotel> getHotels() {
		return this.hotels;
	}

	public void setHotels(Set<Hotel> hotels) {
		this.hotels = hotels;
	}

}
