// default package
// Generated Nov 13, 2022, 12:55:12 AM by Hibernate Tools 4.3.6.Final
package com.hotelbooking.model;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * AgentContactInfo generated by hbm2java
 */
@Entity
@Table(name = "agent_contact_info", catalog = "hotel_booking", uniqueConstraints = @UniqueConstraint(columnNames = "Agent_ID"))
public class AgentContactInfo implements java.io.Serializable {

	private int agentContactInfoId;
	private Agent agent;
	private String contactNum;
	private String email;
	private String address;

	public AgentContactInfo() {
	}

	public AgentContactInfo(int agentContactInfoId) {
		this.agentContactInfoId = agentContactInfoId;
	}

	public AgentContactInfo(int agentContactInfoId, Agent agent, String contactNum, String email, String address) {
		this.agentContactInfoId = agentContactInfoId;
		this.agent = agent;
		this.contactNum = contactNum;
		this.email = email;
		this.address = address;
	}

	@Id

	@Column(name = "Agent_Contact_Info_ID", unique = true, nullable = false)
	public int getAgentContactInfoId() {
		return this.agentContactInfoId;
	}

	public void setAgentContactInfoId(int agentContactInfoId) {
		this.agentContactInfoId = agentContactInfoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Agent_ID", unique = true)
	public Agent getAgent() {
		return this.agent;
	}

	public void setAgent(Agent agent) {
		this.agent = agent;
	}

	@Column(name = "Contact_Num")
	public String getContactNum() {
		return this.contactNum;
	}

	public void setContactNum(String contactNum) {
		this.contactNum = contactNum;
	}

	@Column(name = "Email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "Address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

}
