package com.hotelbooking.model;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Agent generated by hbm2java
 */
@Entity
@Table(name = "agent", catalog = "hotel_booking")
public class Agent implements java.io.Serializable {

	private int agentId;
	private String displayName;
	private String bio;
	private String coverImg;
	private String avatarImg;
	private Set<Hotel> hotels = new HashSet<Hotel>(0);
	private Set<AgentContactInfo> agentContactInfos = new HashSet<AgentContactInfo>(0);

	public Agent() {
	}

	public Agent(int agentId) {
		this.agentId = agentId;
	}

	public Agent(int agentId, String displayName, String bio, String coverImg, String avatarImg, Set<Hotel> hotels,
			Set<AgentContactInfo> agentContactInfos) {
		this.agentId = agentId;
		this.displayName = displayName;
		this.bio = bio;
		this.coverImg = coverImg;
		this.avatarImg = avatarImg;
		this.hotels = hotels;
		this.agentContactInfos = agentContactInfos;
	}

	@Id

	@Column(name = "Agent_ID", unique = true, nullable = false)
	public int getAgentId() {
		return this.agentId;
	}

	public void setAgentId(int agentId) {
		this.agentId = agentId;
	}

	@Column(name = "Display_Name")
	public String getDisplayName() {
		return this.displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	@Column(name = "Bio")
	public String getBio() {
		return this.bio;
	}

	public void setBio(String bio) {
		this.bio = bio;
	}

	@Column(name = "Cover_Img")
	public String getCoverImg() {
		return this.coverImg;
	}

	public void setCoverImg(String coverImg) {
		this.coverImg = coverImg;
	}

	@Column(name = "Avatar_Img")
	public String getAvatarImg() {
		return this.avatarImg;
	}

	public void setAvatarImg(String avatarImg) {
		this.avatarImg = avatarImg;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "agent")
	public Set<Hotel> getHotels() {
		return this.hotels;
	}

	public void setHotels(Set<Hotel> hotels) {
		this.hotels = hotels;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "agent")
	public Set<AgentContactInfo> getAgentContactInfos() {
		return this.agentContactInfos;
	}

	public void setAgentContactInfos(Set<AgentContactInfo> agentContactInfos) {
		this.agentContactInfos = agentContactInfos;
	}

}
