// default package
// Generated Nov 13, 2022, 12:55:12 AM by Hibernate Tools 4.3.6.Final
package com.hotelbooking.model;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Amenities generated by hbm2java
 */
@Entity
@Table(name = "amenities", catalog = "hotel_booking")
public class Amenities implements java.io.Serializable {

	private int amenitiesId;
	private Boolean freeWifi;
	private Boolean freeParking;
	private Boolean freePool;
	private Boolean freeFreshener;
	private Set<HotelDetail> hotelDetails = new HashSet<HotelDetail>(0);

	public Amenities() {
	}

	public Amenities(int amenitiesId) {
		this.amenitiesId = amenitiesId;
	}

	public Amenities(int amenitiesId, Boolean freeWifi, Boolean freeParking, Boolean freePool, Boolean freeFreshener,
			Set<HotelDetail> hotelDetails) {
		this.amenitiesId = amenitiesId;
		this.freeWifi = freeWifi;
		this.freeParking = freeParking;
		this.freePool = freePool;
		this.freeFreshener = freeFreshener;
		this.hotelDetails = hotelDetails;
	}

	@Id

	@Column(name = "Amenities_ID", unique = true, nullable = false)
	public int getAmenitiesId() {
		return this.amenitiesId;
	}

	public void setAmenitiesId(int amenitiesId) {
		this.amenitiesId = amenitiesId;
	}

	@Column(name = "Free_Wifi")
	public Boolean getFreeWifi() {
		return this.freeWifi;
	}

	public void setFreeWifi(Boolean freeWifi) {
		this.freeWifi = freeWifi;
	}

	@Column(name = "Free_Parking")
	public Boolean getFreeParking() {
		return this.freeParking;
	}

	public void setFreeParking(Boolean freeParking) {
		this.freeParking = freeParking;
	}

	@Column(name = "Free_Pool")
	public Boolean getFreePool() {
		return this.freePool;
	}

	public void setFreePool(Boolean freePool) {
		this.freePool = freePool;
	}

	@Column(name = "Free_Freshener")
	public Boolean getFreeFreshener() {
		return this.freeFreshener;
	}

	public void setFreeFreshener(Boolean freeFreshener) {
		this.freeFreshener = freeFreshener;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "amenities")
	public Set<HotelDetail> getHotelDetails() {
		return this.hotelDetails;
	}

	public void setHotelDetails(Set<HotelDetail> hotelDetails) {
		this.hotelDetails = hotelDetails;
	}

}
