package com.hotelbooking.model;
// default package
// Generated Nov 16, 2022, 11:06:54 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "category", catalog = "hotel_booking")
public class Category implements java.io.Serializable {

	private Integer categoryId;
	private String categoryName;
	private Integer size;
	private Set<Hotel> hotels = new HashSet<Hotel>(0);
	private Set<Hotel> hotels_1 = new HashSet<Hotel>(0);

	public Category() {
	}

	public Category(String categoryName, Integer size, Set<Hotel> hotels, Set<Hotel> hotels_1) {
		this.categoryName = categoryName;
		this.size = size;
		this.hotels = hotels;
		this.hotels_1 = hotels_1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Category_ID", unique = true, nullable = false)
	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "Category_Name")
	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	@Column(name = "Size")
	public Integer getSize() {
		return this.size;
	}

	public void setSize(Integer size) {
		this.size = size;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "category")
	public Set<Hotel> getHotels() {
		return this.hotels;
	}

	public void setHotels(Set<Hotel> hotels) {
		this.hotels = hotels;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "category")
	public Set<Hotel> getHotels_1() {
		return this.hotels_1;
	}

	public void setHotels_1(Set<Hotel> hotels_1) {
		this.hotels_1 = hotels_1;
	}

}
