// default package
// Generated Nov 13, 2022, 12:55:12 AM by Hibernate Tools 4.3.6.Final
package com.hotelbooking.model;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "category", catalog = "hotel_booking")
public class Category implements java.io.Serializable {

	private CategoryId id;
	private Integer size;
	private Set<Hotel> hotels = new HashSet<Hotel>(0);

	public Category() {
	}

	public Category(CategoryId id) {
		this.id = id;
	}

	public Category(CategoryId id, Integer size, Set<Hotel> hotels) {
		this.id = id;
		this.size = size;
		this.hotels = hotels;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "categoryId", column = @Column(name = "Category_ID", nullable = false)),
			@AttributeOverride(name = "categoryName", column = @Column(name = "Category_Name", nullable = false)) })
	public CategoryId getId() {
		return this.id;
	}

	public void setId(CategoryId id) {
		this.id = id;
	}

	@Column(name = "Size")
	public Integer getSize() {
		return this.size;
	}

	public void setSize(Integer size) {
		this.size = size;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "category")
	public Set<Hotel> getHotels() {
		return this.hotels;
	}

	public void setHotels(Set<Hotel> hotels) {
		this.hotels = hotels;
	}

}
