// default package
// Generated Nov 13, 2022, 12:55:12 AM by Hibernate Tools 4.3.6.Final
package com.hotelbooking.model;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CategoryId generated by hbm2java
 */
@Embeddable
public class CategoryId implements java.io.Serializable {

	private int categoryId;
	private String categoryName;

	public CategoryId() {
	}

	public CategoryId(int categoryId, String categoryName) {
		this.categoryId = categoryId;
		this.categoryName = categoryName;
	}

	@Column(name = "Category_ID", nullable = false)
	public int getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "Category_Name", nullable = false)
	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CategoryId))
			return false;
		CategoryId castOther = (CategoryId) other;

		return (this.getCategoryId() == castOther.getCategoryId())
				&& ((this.getCategoryName() == castOther.getCategoryName())
						|| (this.getCategoryName() != null && castOther.getCategoryName() != null
								&& this.getCategoryName().equals(castOther.getCategoryName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCategoryId();
		result = 37 * result + (getCategoryName() == null ? 0 : this.getCategoryName().hashCode());
		return result;
	}

}
