// default package
// Generated Nov 13, 2022, 12:55:12 AM by Hibernate Tools 4.3.6.Final
package com.hotelbooking.model;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Contact generated by hbm2java
 */
@Entity
@Table(name = "contact", catalog = "hotel_booking")
public class Contact implements java.io.Serializable {

	private int contactId;
	private String message;
	private String email;
	private String contactNum;

	public Contact() {
	}

	public Contact(int contactId) {
		this.contactId = contactId;
	}

	public Contact(int contactId, String message, String email, String contactNum) {
		this.contactId = contactId;
		this.message = message;
		this.email = email;
		this.contactNum = contactNum;
	}

	@Id

	@Column(name = "Contact_ID", unique = true, nullable = false)
	public int getContactId() {
		return this.contactId;
	}

	public void setContactId(int contactId) {
		this.contactId = contactId;
	}

	@Column(name = "Message")
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@Column(name = "Email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "Contact_Num")
	public String getContactNum() {
		return this.contactNum;
	}

	public void setContactNum(String contactNum) {
		this.contactNum = contactNum;
	}

}
