// default package
// Generated Nov 13, 2022, 12:55:12 AM by Hibernate Tools 4.3.6.Final
package com.hotelbooking.model;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * HotelDetail generated by hbm2java
 */
@Entity
@Table(name = "hotel_detail", catalog = "hotel_booking", uniqueConstraints = @UniqueConstraint(columnNames = "Hotel_ID"))
public class HotelDetail implements java.io.Serializable {

	private int hotelDetailId;
	private Amenities amenities;
	private Hotel hotel;
	private String description;
	private String location;
	private String address;
	private Long price;
	private Integer rooms;

	public HotelDetail() {
	}

	public HotelDetail(int hotelDetailId) {
		this.hotelDetailId = hotelDetailId;
	}

	public HotelDetail(int hotelDetailId, Amenities amenities, Hotel hotel, String description, String location,
			String address, Long price, Integer rooms) {
		this.hotelDetailId = hotelDetailId;
		this.amenities = amenities;
		this.hotel = hotel;
		this.description = description;
		this.location = location;
		this.address = address;
		this.price = price;
		this.rooms = rooms;
	}

	@Id

	@Column(name = "Hotel_Detail_ID", unique = true, nullable = false)
	public int getHotelDetailId() {
		return this.hotelDetailId;
	}

	public void setHotelDetailId(int hotelDetailId) {
		this.hotelDetailId = hotelDetailId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Amenities_ID")
	public Amenities getAmenities() {
		return this.amenities;
	}

	public void setAmenities(Amenities amenities) {
		this.amenities = amenities;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Hotel_ID", unique = true)
	public Hotel getHotel() {
		return this.hotel;
	}

	public void setHotel(Hotel hotel) {
		this.hotel = hotel;
	}

	@Column(name = "Description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "Location")
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "Address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "Price", precision = 10, scale = 0)
	public Long getPrice() {
		return this.price;
	}

	public void setPrice(Long price) {
		this.price = price;
	}

	@Column(name = "Rooms")
	public Integer getRooms() {
		return this.rooms;
	}

	public void setRooms(Integer rooms) {
		this.rooms = rooms;
	}

}
